const actionTypes = {
  LOAD_CHARACTERS_LIST: 'LOAD_CHARACTERS_LIST',
  LOAD_LIST_ERROR: 'LOAD_LIST_ERROR',
  LOAD_SPECIES_LIST: 'LOAD_SPECIES_LIST',
  LOAD_LIST_SPECIES_ERROR: 'LOAD_LIST_SPECIES_ERROR'

};
  
  export default actionTypes;
  